updated v0.8 server setup cicd workflow

diff --git a/.github/workflows/access-server.yml b/.github/workflows/access-server.yml
--- a/.github/workflows/access-server.yml
+++ b/.github/workflows/access-server.yml
@@ -5,19 +5,42 @@ jobs:
     name: Access server
     runs-on: ubuntu-latest
     steps:
+      - name: Check Dockerfile Changes
+        id: dockerfile_changed
+        run: |
+          changed_files=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep "Dockerfile")
+          if [ -n "$changed_files" ]; then
+            echo "Dockerfile has changed. Removing old container and image."
+            echo "::set-output name=changed::true"
+          else
+            echo "Dockerfile has not changed. Continuing with existing container and image."
+            echo "::set-output name=changed::false"
+          fi
+      - name: Remove Old Container and Image
+        if: steps.dockerfile_changed.outputs.changed == 'true'
+        run: |
+          docker ps -a
+          docker rm -f $(docker ps -aq)
+          docker rmi -f $(docker images -q)
       - name: Create a file
         uses: appleboy/ssh-action@v1.0.0
         with:
           host: ${{ secrets.HOST_DNS }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
+          run: |
             sudo apt-get -y update
             cd django_project/django-deployment-guide
-            ls
             git pull origin main
-            docker ps -a
-            docker rm -f $(docker ps -aq)
-            docker rmi -f $(docker images -q)
-            docker build -t my-python-app:1.0 .
+
+            # Add error handling for Git pull
+            if [ $? -ne 0 ]; then
+              echo "Error: Git pull failed."
+              exit 1
+            fi
+            
+            # Build and run Docker container only if Dockerfile has changed
+            if [ "${{ steps.dockerfile_changed.outputs.changed }}" == 'true' ]; then
+              docker build -t my-python-app:1.0 .
+            fi
             docker run -p 8000:8000 my-python-app:1.0
